2024-11-12 09:10:56,752 - app.logger - INFO - 检测当前分支是否干净.....
2024-11-12 09:11:32,639 - app.logger - INFO - 当前分支不干净，请先提交代码，再执行该脚本
2024-11-12 09:11:32,639 - app.logger - WARNING - ==================================================报错信息如下：
2024-11-12 09:11:32,644 - app.logger - WARNING - Traceback (most recent call last):
  File "D:\sangfor\filesyncpro\app\base.py", line 216, in run_action
    self.action()
  File "D:\sangfor\filesyncpro\app\base.py", line 208, in action
    self.initialization()
  File "D:\sangfor\filesyncpro\app\base.py", line 38, in initialization
    raise AssertionError("当前分支不干净，未新增、删除、修改文件")
AssertionError: 当前分支不干净，未新增、删除、修改文件

2024-11-12 09:11:32,672 - app.logger - WARNING - ==================================================请检查错误并修改后重新执行！
